[package]
authors = ["rise0chen <rise0chen@163.com>"]
description = "Clock program"
edition = "2018"
license-file = "LICENSE"
name = "time-clock"
readme = "./README.md"
repository = "https://github.com/rise0chen/clock_source.git"
version = "0.1.0"
